name: Build and Release Velvet Studio

on:
  push:
    tags:
      - 'v*' # Trigger build when pushing tags like v5.3.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # Build for both Mac and Windows
        os: [macos-latest, windows-latest]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm ci
        
      # Build the React application
      - name: Build Vite App
        run: npm run build
        
      - name: Transpile Server to CommonJS
        run: npx esbuild server.js --bundle --platform=node --format=cjs --outfile=dist/server.cjs
        
      # Package the Electron application using electron-builder
      - name: Publish Electron App
        env:
          # GitHub automatically generates this token for actions, allowing it to upload releases
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --config electron-builder.json --publish always
